// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Park struct {
	ID          uuid.UUID
	NpsID       string
	FullName    string
	ParkCode    string
	Description string
	Designation string
	Activities  json.RawMessage
	Topics      json.RawMessage
	Details     json.RawMessage
	CreatedAt   time.Time
}

type ParkState struct {
	ParkID    uuid.UUID
	StateCode string
}

type State struct {
	Code string
	Name sql.NullString
}
