// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parks.sql

package database

import (
	"context"
)

const getParkByState = `-- name: GetParkByState :many
SELECT p.full_name, park_states.state_code
FROM parks as p
JOIN park_states
ON p.id = park_states.park_id
WHERE park_states.state_code = $1
ORDER BY 
  CASE WHEN $1 = 'full_name' THEN parks.full_name END ASC,
  CASE WHEN $1 = 'designation' THEN parks.designation END ASC,
    p.id ASC
LIMIT $2
`

type GetParkByStateParams struct {
	StateCode string
	Limit     int32
}

type GetParkByStateRow struct {
	FullName  string
	StateCode string
}

func (q *Queries) GetParkByState(ctx context.Context, arg GetParkByStateParams) ([]GetParkByStateRow, error) {
	rows, err := q.db.QueryContext(ctx, getParkByState, arg.StateCode, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParkByStateRow
	for rows.Next() {
		var i GetParkByStateRow
		if err := rows.Scan(&i.FullName, &i.StateCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParks = `-- name: GetParks :many
SELECT full_name, designation
FROM parks
ORDER BY 
  CASE WHEN $1 = 'full_name' THEN parks.full_name END ASC,
  CASE WHEN $1 = 'designation' THEN parks.designation END ASC,
    parks.park_code ASC
LIMIT $2
`

type GetParksParams struct {
	Column1 interface{}
	Limit   int32
}

type GetParksRow struct {
	FullName    string
	Designation string
}

func (q *Queries) GetParks(ctx context.Context, arg GetParksParams) ([]GetParksRow, error) {
	rows, err := q.db.QueryContext(ctx, getParks, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParksRow
	for rows.Next() {
		var i GetParksRow
		if err := rows.Scan(&i.FullName, &i.Designation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
