// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: parks.sql

package database

import (
	"context"
)

const getParks = `-- name: GetParks :many
SELECT full_name, designation
FROM parks
ORDER BY full_name ASC
`

type GetParksRow struct {
	FullName    string
	Designation string
}

func (q *Queries) GetParks(ctx context.Context) ([]GetParksRow, error) {
	rows, err := q.db.QueryContext(ctx, getParks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParksRow
	for rows.Next() {
		var i GetParksRow
		if err := rows.Scan(&i.FullName, &i.Designation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
